#!/bin/sh

# Function to print colored output that works in both zsh and bash
color_echo() {
  color="$1"
  shift
  if [ -t 1 ]; then  # Check if stdout is a terminal
    printf "$color%b${NC}\n" "$*"
  else
    printf "%b\n" "$*"
  fi
}

# ANSI color codes
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
NC='\033[0m'  # No Color

# If you update code_freeze.yaml, make sure that all freezes are valid.
if [ `git diff --cached --name-only | grep '^code_freeze.yaml$' | wc -l` -eq 1 ]
then
  if ! ./script/validate_code_freeze.rb
  then
    echo ""
    color_echo "$red" "--------------------------------- Commit ERROR ------------------------------------"
    color_echo "" "Your changes to code_freeze.yaml contain invalid entries."
    color_echo "" "You can verify your changes manually by running \`./script/validate_code_freeze.rb\`."
    color_echo "$red" "------------------------------- END Commit ERROR ----------------------------------"
    exit 1
  fi
fi

exit 0
